Fix config and add custom header support
uesteibar/neuron pull request #4
Opened 2017-07-25 07:33 UTC by kh0r

2017-08-18 15:07 UTC, uesteibar requested changes
First, very very very sorry I missed this! Didn't see the pull request until now 😢 

Second, thank you for the work done here! I left some comments that we should fix, and after that this would be ready to be merged and released.

2017-08-18 15:07 UTC, uesteibar commented on lib/neuron/config.ex
> +  end
Could you add a blank line right after this?

2017-08-18 15:07 UTC, uesteibar commented on lib/neuron/config.ex
> +  def set(:global, url: url_value) do
I think the renaming of `value` to `url_value` doesn't add any extra information, can you change it back to `value`? `url:` is already giving us that info.

2017-08-18 15:07 UTC, uesteibar commented on lib/neuron/config.ex
> +  def set(:global, headers: header_value) do
Same here about `header_value`. We should go with `value`.

2017-08-18 15:07 UTC, uesteibar commented on lib/neuron/config.ex
> +    Process.put(:url, url_value)
Would be good to rename this `:url` into something that contains `neuron` (`:neuron_url` should be good enough). This way we avoid colliding with variables set by code outside of this library, since it's nor running as an standalone process.

2017-08-18 15:07 UTC, uesteibar commented on lib/neuron/config.ex
> +    Process.put(:headers, header_value)
Same about renaming `:headers` to `:neuron_headers`.

2017-08-18 15:07 UTC, uesteibar commented on lib/neuron/config.ex
> +      iex>Neuron.Config.set(headers: ["name", "value"]); Neuron.Config.get(:headers)
As I see in [here](https://github.com/uesteibar/neuron/pull/4/files#diff-09d8e6a4ca1b3cb6ef8036dd32a146e9R37), this should actually be `["name": "value"]`.

2017-08-18 15:07 UTC, uesteibar commented on lib/neuron/config.ex
> +    get_config_for(current_context(key))[key]
Maybe we could rewrite this as something like:

```elixir
key
|> get_current_context
|> get_config
|> Map.get(key)
```

Some renaming would have to be done but reads much better IMHO.

2017-08-18 15:07 UTC, uesteibar commented on lib/neuron/connection.ex
> +  def post(url, _) when is_nil(url) do
Good point

2017-08-18 15:07 UTC, uesteibar commented on lib/neuron/connection.ex
> +    |> header_conf
Should be enough doing `Config.get(:headers) || []`.
This way we can remove the functions below.

2017-08-18 15:07 UTC, uesteibar commented on test/neuron/connection_test.exs
> +      # reset
I don't think this comments is needed :)

2017-08-18 15:07 UTC, uesteibar commented on lib/neuron/connection.ex
> +  def build_headers() do
Do we need this function to be public? If not, I'd say we make it private.

2017-08-18 15:07 UTC, uesteibar commented on mix.exs
> +  @version "0.3.0"
Can you revert this change? I will do this myself in a separate commit once this PR is merged.

2017-08-18 15:07 UTC, uesteibar commented on test/neuron/connection_test.exs
> +    test "empty params" do
Can we rename this example to `sets content-type as default header`?

2017-08-18 15:07 UTC, uesteibar commented on test/neuron/connection_test.exs
> +
We don't need/want this empty blank line here

2017-08-18 15:07 UTC, uesteibar commented on test/neuron/connection_test.exs
> +  describe "headers function" do
This describe should be `build_headers/0`, since that's the function you're testing.

2017-08-18 15:07 UTC, uesteibar commented on lib/neuron/connection.ex
> +      %{},
If I'm not missing anything, this argument shouldn't be here, right?
https://hexdocs.pm/httpoison/HTTPoison.html#post/4

2017-08-18 15:10 UTC, uesteibar commented
Also, if you have a look at the [contributing section](https://github.com/uesteibar/neuron/commits/master) of the readme, we use the *conventional commits standard conventions* to make generating changelogs much easier. Would be great if you change the commit message to something compliant with this convention.

2017-08-24 07:00 UTC, leifg commented
I'm happy to address these changes in a separate branch if that's fine with @kh0r

2017-08-24 07:33 UTC, uesteibar commented
@leifg if @kh0r is fine with it, sounds good to me 🎉 thanks!!

2017-08-24 20:04 UTC, leifg commented on lib/neuron/connection.ex
> +  def build_headers() do
It's used in the tests

2017-08-24 20:11 UTC, leifg commented
PR is open here #5 

To comply with the contribution guidelines I had to overwrite commit message.

2017-08-25 15:31 UTC, kh0r commented
Hi! Sorry for the late replay, I'm definitely fine with that :)

2017-08-25 19:47 UTC, uesteibar commented
@kh0r no worries! thanks, I'll close this PR and we can continue on the other one :)

2017-08-25 19:48 UTC, closed without merging